name: Spglib PyPI Wheel builds

on:
  push:
    branches:
      - rc
      - rctest

jobs:
  build-wheel:
    name: Build ${{ matrix.platform }} wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - manylinux1_x86_64
          - manylinux1_i686
          - manylinux2014_x86_64
          - manylinux2014_aarch64
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        if: matrix.platform == 'manylinux2014_aarch64'
        uses: docker/setup-qemu-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Build manylinux Python wheels manylinux1_x86_64
        if: matrix.platform == 'manylinux1_x86_64'
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux1_x86_64
        with:
          python-versions: "cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39"
          pre-build-command: 'sh pre-build-script.sh'
          package-path: ./python
      - name: Build manylinux Python wheels manylinux1_i686
        if: matrix.platform == 'manylinux1_i686'
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux1_i686
        with:
          python-versions: "cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39"
          pre-build-command: 'sh pre-build-script.sh'
          package-path: ./python
      - name: Build manylinux Python wheels manylinux2014_x86_64
        if: matrix.platform == 'manylinux2014_x86_64'
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_x86_64
        with:
          python-versions: "cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39"
          pre-build-command: 'sh pre-build-script.sh'
          package-path: ./python
      - name: Build manylinux Python wheels manylinux2014_aarch64
        if: matrix.platform == 'manylinux2014_aarch64'
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_aarch64
        with:
          python-versions: "cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39"
          pre-build-command: 'sh pre-build-script.sh'
          package-path: ./python

      - name: copy manylinux wheels
        run: |
          mkdir dist
          cp ./python/dist/*manylinux*whl dist

      - name: Publish package to TestPyPI
        if: startsWith(github.ref, 'refs/heads/rc')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: ./dist
