name: ðŸš€ release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/step_test.yaml
  build-wheel:
    name: build-wheel
    needs: [ tests ]
    uses: ./.github/workflows/step_build-wheel.yaml
  upload_pypi:
    name: Upload to PyPI repository
    needs: [ tests, build-wheel ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/spglib/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish package to TestPyPI
        if: ${{ contains(github.ref, 'rc') }}
        # TODO: Maybe we can move this to main PyPI since it is marked rc
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package to PyPI
        if: ${{ !contains(github.ref, 'rc') }}
        uses: pypa/gh-action-pypi-publish@release/v1
  release:
    needs: [ upload_pypi ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          name: Spglib ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') }}
          generate_release_notes: true
